#+TITLE: About Me
#+HTML_HEAD_EXTRA: <style type="text/css">.title {text-align: center;}</style>

/Hi there fellow hackers, scripters, and computer enthusiasts!/

My name is Tyler, but online you'll find me going by my alias: /Tdback/.

A little bit about me: to start, I love Linux and am an avid scripter! You'll most often find me hovered over a keyboard writing yet /another/ bash script to automate a boring or tedious task, all so I can get back to doing (in my opinion) more important things like discovering obscure Linux terminal hacks, starting yet another home project, or playing on my Wii and Gamecube emulator, reminiscing in the nostalgia of my favorite childhood games. I absolutely love exploring new technology as well as exploring the rich and oftentimes interesting history of computers and programming.

When it comes to the scripting, most of what I write in nowadays comprises of bash scripts, text processing tools like sed, grep, and Awk, the occasional dash of Python for machine learning model development, and now a bit of PowerShell! When I'm not writing scripts to shave seconds off my workflow, I'm oftentimes spending too much time customizing my operating system, Arch Linux, or text editor of choice, Emacs. In fact, this entire website was written using org-mode, an Emacs major mode for keeping notes, writing documents, and generating HTML from markdown-like sytnax (it's org-mode syntax, which in my opinion is superior to that of markdown). If you'd like to know why I choose to use Linux as my operating system, and not Windows, I wrote a blog post about it [[../blog/whylinux.org][here]]!

As for the all-important hardware that powers my tech hobbies and endeavors, I mainly use both a desktop that I've built and a MacBook Pro. As for my other boxes, I am currently working on several home server projects. If you want to know more about specifications for the hardware I use, you can find that [[../etc/config.org][here]].

Outside of technology, you can expect to find me brewing teas or trying out new coffees with my great friend Lane (whose site you can find [[https://www.lanerj.com/home][here]]), watching horror movies with my fiancee (80's slashers are by far my favorite, with Scream sitting comfortably at the top of my list), listening to rock music (Breaking Benjamin is the GOAT), playing videogames with the boys, or going for a run to stretch my legs. 

* Certifications
*** Security+
*** AWS Certified Cloud Practioner (CCP)
*** Network+ (in progress)

* Work Experience
*** Cyber Security Engineer (Intern) - /North Dakota Information Technology (NDIT)/
- January 2023 - PRESENT
- Cybersecurity engineering intern on the governance risk and compliance security team.
*** Desktop Support Technician - /Ferris State University/
- May 2021 - PRESENT
- Troubleshooting and configuration of campus technologies and computer maintenance, including: Windows, Mac, Office 365, Active Directory, PrinterLogic, and Cherwell
*** Teacher Assistant - /Ferris State University/
- August 2022 - March 2022
- Python Programming. For two semesters, hosted open labs and helped lead classes to provide assistance and additional instruction for students.
*** Assistant Instructor - /ProKarate/
- July 2014 - March 2020
- Assistant Sensei teaching martial arts to adults and children.

* Contact Information
Feel free to reach out to me [at] =tylerdback@pm.me= if you have any questions about technology, my thoughts on a topic, or just want to talk! Just make sure to mention you viewed my website, or I might mistake you for spam :)

You can also find me on [[https://www.linkedin.com/in/tyler-dback/][LinkedIn]]! Feel free to follow me or send me a message, but again, make sure to mention that you viewed my site so I don't mistake you for spam :)

And finally, don't forget to check out my [[https://github.com/Tdback][GitHub]]! There you can find all my dotfiles (configuration files for my desktop, laptop, etc.) and any current or past projects I'm working on.

/Hack away, hack away my friends!/
